/*** Generated by streamline 0.3.6 (callbacks) - DO NOT EDIT ***/
var __rt=require('streamline/lib/callbacks/runtime').runtime(__filename),__func=__rt.__func,__cb=__rt.__cb,__tryCatch=__rt.__tryCatch,__propagate=__rt.__propagate,__trap=__rt.__trap,__future=__rt.__future,__setEF=__rt.__setEF,__g=__rt.__g;
/*     1 */ var common = require("../common");
/*    17 */ var fs = require("fs");
/*    18 */ var path = require("path");
/*    19 */ var url = require("url");
/*    20 */ var crypto = require("crypto");
/*    21 */ var pfx2pem = require("../../util/certificates/pkcs").pfx2pem;
/*    22 */ var Channel = require("../channel");
/*    23 */ var async = require("async");
/*    24 */ var child_process = require("child_process");
/*    25 */ var utils = require("../utils");
/*    26 */ var constants = require("../constants");
/*    27 */ var cacheUtils = require("../cacheUtils");
/*    29 */ exports.init = function(cli) {
/*    31 */   var log = cli.output;
/*    33 */   function getChannel() {
/*    34 */     var account = cli.category("account"), pem = account.managementCertificate(), host = ((process.env.AZURE_ENDPOINT_HOST || account.endpointHost()) || constants.DEFAULT_MANAGEMENT_HOSTNAME), port = ((process.env.AZURE_ENDPOINT_PORT || account.endpointPort()) || constants.DEFAULT_HTTPS_PORT);
/*    39 */     var channel = new Channel({
/*    40 */       host: host,
/*    41 */       port: port,
/*    42 */       key: pem.key,
/*    43 */       cert: pem.cert
/*    44 */     }).header("x-ms-version", "2011-02-25");
/*    46 */     var proxyString = (((process.env.HTTPS_PROXY || process.env.https_proxy) || process.env.ALL_PROXY) || process.env.all_proxy);
/*    52 */     if ((proxyString !== undefined)) {
/*    53 */       var proxyUrl = url.parse(proxyString);
/*    54 */       if (((proxyUrl.protocol !== "http:") && (proxyUrl.protocol !== "https:"))) {
/*    57 */         proxyUrl = url.parse(("http://" + proxyString));
                  }
                ;
/*    60 */       channel = channel.add({
/*    60 */         proxy: proxyUrl
                  });
                }
              ;
/*    63 */     return channel;
              };
/*    66 */   var site = cli.category("site").description("Commands to manage your web sites");
/*    69 */   site.command("list").whiteListPowershell().description("List your web sites").option("-s, --subscription <id>", "use the subscription id").execute(function __1(options, _) {
                var parameters, sites, s;
                var __frame = {
                  name: "__1",
                  line: 73
                };
                return __func(_, this, arguments, __1, 1, __frame, function __$__1() {
/*    74 */       parameters = {
/*    75 */         subscription: cli.category("account").lookupSubscriptionId(options.subscription)
                  };
/*    78 */       return site.doSitesGet(parameters, __cb(_, __frame, 5, 22, function ___(__0, __1) {
                    sites = __1;
/*    80 */         if ((sites && (sites.length > 0))) {
/*    81 */           for (s in sites) {
/*    82 */             sites[s] = clean(sites[s]);
                      };
/*    85 */           log.table(sites, function(row, s) {
/*    86 */             row.cell("Name", s.Name);
/*    87 */             row.cell("State", s.State);
/*    88 */             row.cell("Host names", s.HostNames);
                      });
                    }
/*    90 */          else {
/*    91 */           log.info("No sites created yet. You can create new sites using \"azure site create\" or through the portal.");
                    }
                  ;
                    _();
                  }, true));
                });
              });
/*    95 */   function choose(data, callback) {
/*    96 */     cli.choose(data, function(x) {
/*    96 */       callback(undefined, x);
                });
              };
/*    98 */   function prompt(label, callback) {
/*    99 */     cli.prompt(label, function(x) {
/*    99 */       callback(undefined, x);
                });
              };
/*   101 */   function confirm(label, callback) {
/*   102 */     cli.confirm(label, function(x) {
/*   103 */       if (!x) {
/*   104 */         log.warn("The operation was cancelled by the user");
                  }
                ;
/*   106 */       callback(undefined, x);
                });
              };
/*   109 */   site.confirm = confirm;
/*   111 */   site.command("create [name]").whiteListPowershell().description("Create a new web site and local directory").option("-s, --subscription <id>", "use the subscription id").option("--location <location>", "the geographic region to create the website").option("--hostname <hostname>", "custom host name to use").option("--git", "configure git on web site and local folder").option("--c9", "c9 mode").execute(function __2(nameArg, options, _) {
                var context;
/*   143 */     function promptForSiteName(_) {
                  var __frame = {
                    name: "promptForSiteName",
                    line: 143
                  };
                  return __func(_, this, arguments, promptForSiteName, 0, __frame, function __$promptForSiteName() {
/*   144 */         log.silly("promptForSiteName");
                    return (function __$promptForSiteName(__then) {
/*   145 */           if ((context.site.name === undefined)) {
/*   146 */             log.help("Need a site name");
/*   147 */             return prompt("Name: ", __cb(_, __frame, 4, 34, function ___(__0, __1) {
/*   147 */               context.site.name = __1;
                          __then();
                        }, true));
                      }
                       else {
                        __then();
                      }
                    ;
                    })(_);
                  });
                };
/*   151 */     function determineIfSiteExists(_) {
                  var sites, hits;
                  var __frame = {
                    name: "determineIfSiteExists",
                    line: 151
                  };
                  return __func(_, this, arguments, determineIfSiteExists, 0, __frame, function __$determineIfSiteExists() {
/*   152 */         log.silly("determineIfSiteExists");
/*   153 */         return site.doSitesGet(context, __cb(_, __frame, 2, 24, function ___(__0, __1) {
                      sites = __1;
/*   154 */           hits = sites.filter(function(item) {
/*   155 */             return utils.ignoreCaseEquals(item.Name, context.site.name);
                      });
/*   157 */           if ((hits.length === 1)) {
/*   158 */             log.info("Updating existing site");
/*   159 */             context.flags.siteExists = true;
/*   160 */             if ((context.site.webspace === undefined)) {
/*   161 */               context.site.webspace = hits[0].WebSpace;
/*   162 */               log.verbose("Existing site location is ", context.site.webspace);
                        }
                         else {
/*   163 */               if ((context.site.webspace !== hits[0].WebSpace)) {
/*   164 */                 return _(new Error(((("Expected location " + context.site.webspace) + " but was ") + hits[0].WebSpace)));
                          }
                        ;
                        }
                      ;
                      }
                    ;
                      _();
                    }, true));
                  });
                };
/*   169 */     function promptForLocation(_) {
                  var spaces, displayNameMatches;
                  var __frame = {
                    name: "promptForLocation",
                    line: 169
                  };
                  return __func(_, this, arguments, promptForLocation, 0, __frame, function __$promptForLocation() {
/*   170 */         log.silly("promptForLocation");
/*   171 */         return cacheUtils.readSpaces(context, __cb(_, __frame, 2, 25, function ___(__0, __1) {
                      spaces = __1;
                      return (function __$promptForLocation(__then) {
/*   172 */             if ((!spaces || !spaces.length)) {
/*   173 */               return site.doSpacesGet(context, __cb(_, __frame, 4, 23, function ___(__0, __2) {
/*   173 */                 spaces = __2;
                            __then();
                          }, true));
                        }
                         else {
                          __then();
                        }
                      ;
                      })(function __$promptForLocation() {
/*   176 */             if ((context.site.webspace !== undefined)) {
/*   178 */               displayNameMatches = spaces.filter(function(space) {
/*   179 */                 return (space.GeoRegion === context.site.webspace);
                          });
/*   181 */               if ((displayNameMatches.length === 1)) {
/*   182 */                 context.site.webspace = displayNameMatches[0].Name;
                          }
                        ;
                        }
                      ;
/*   186 */             if ((context.site.webspace !== undefined)) {
                          return _(null);
                        }
                      ;
                        return (function __$promptForLocation(__then) {
/*   191 */               if ((spaces.length === 0)) {
/*   192 */                 return portalCreateSiteInstruction(context, __cb(_, __frame, 23, 14, function __$promptForLocation() {
/*   193 */                   return _(new Error("First site must be created on portal"));
                            }, true));
                          }
                           else {
                            return (function __$promptForLocation(__then) {
/*   194 */                   if ((spaces.length == 1)) {
/*   195 */                     context.site.webspace = spaces[0].Name;
/*   196 */                     log.info("Using location", context.site.webspace);
                                __then();
                              }
                               else {
/*   198 */                     log.help("Choose a region");
/*   199 */                     return choose(spaces.map(function(space) {
/*   200 */                       return space.GeoRegion;
                                }), __cb(_, __frame, 30, 45, function ___(__0, __3) {
/*   199 */                       context.site.webspace = spaces[__3].Name;
                                  __then();
                                }, true));
                              }
                            ;
                            })(__then);
                          }
                        ;
                        })(_);
                      });
                    }, true));
                  });
                };
/*   205 */     function determineIfCurrentDirectoryIsGitWorkingTree(_) {
                  var isInsideWorkTree, lines;
                  var __frame = {
                    name: "determineIfCurrentDirectoryIsGitWorkingTree",
                    line: 205
                  };
                  return __func(_, this, arguments, determineIfCurrentDirectoryIsGitWorkingTree, 0, __frame, function __$determineIfCurrentDirectoryIsGitWorkingTree() {
/*   206 */         log.silly("determineIfCurrentDirectoryIsGitWorkingTree");
                    return (function ___(__then) {
                      (function ___(_) {
                        __tryCatch(_, function __$determineIfCurrentDirectoryIsGitWorkingTree() {
/*   209 */               return exec("git rev-parse --is-inside-work-tree", __cb(_, __frame, 4, 37, function ___(__0, __1) {
                            isInsideWorkTree = __1;
/*   210 */                 lines = (isInsideWorkTree.stdout + isInsideWorkTree.stderr);
/*   211 */                 context.flags.isGitWorkingTree = lines.split("\n").some(function(line) {
/*   212 */                   return (line === "true");
                            });
                            __then();
                          }, true));
                        });
                      })(function ___(err, __result) {
                        __tryCatch(_, function __$determineIfCurrentDirectoryIsGitWorkingTree() {
                          if (err) {
/*   215 */                 context.flags.isGitWorkingTree = false;
                            __then();
                          }
                           else {
                            _(null, __result);
                          }
                        ;
                        });
                      });
                    })(function ___() {
                      __tryCatch(_, _);
                    });
                  });
                };
/*   219 */     function initGitOnCurrentDirectory(_) {
                  var __frame = {
                    name: "initGitOnCurrentDirectory",
                    line: 219
                  };
                  return __func(_, this, arguments, initGitOnCurrentDirectory, 0, __frame, function __$initGitOnCurrentDirectory() {
/*   220 */         log.silly("initGitOnCurrentDirectoryIfNeeded");
/*   221 */         if (context.flags.isGitWorkingTree) {
                      return _(null);
                    }
                  ;
/*   225 */         if (!options.git) {
                      return _(null);
                    }
                  ;
                    return (function __$initGitOnCurrentDirectory(__then) {
/*   229 */           if (context.c9) {
/*   230 */             context.publishingUsers = ["c9",];
/*   231 */             context.publishingUser = "c9";
                        __then();
                      }
                       else {
/*   233 */             return site.doPublishingUsersGet(context, __cb(_, __frame, 14, 40, function ___(__0, __1) {
/*   233 */               context.publishingUsers = __1;
/*   234 */               return getPublishingUser(context, __cb(_, __frame, 15, 39, function ___(__0, __2) {
/*   234 */                 context.publishingUser = __2;
                            __then();
                          }, true));
                        }, true));
                      }
                    ;
                    })(function __$initGitOnCurrentDirectory() {
/*   237 */           log.info("Executing `git init`");
/*   238 */           return exec("git init", __cb(_, __frame, 19, 12, function __$initGitOnCurrentDirectory() {
                        return (function __$initGitOnCurrentDirectory(__then) {
/*   240 */               if (!path.existsSync(".gitignore")) {
/*   241 */                 log.info("Creating default .gitignore file");
/*   242 */                 return fs.writeFile(".gitignore", "node_modules\nazure_error", __cb(_, __frame, 23, 14, __then, true));
                          }
                           else {
                            __then();
                          }
                        ;
                        })(function __$initGitOnCurrentDirectory() {
/*   245 */               context.flags.isGitWorkingTree = true;
                          _();
                        });
                      }, true));
                    });
                  });
                };
/*   248 */     function copyIisNodeWhenServerJsPresent(_) {
                  var sourcePath;
                  var __frame = {
                    name: "copyIisNodeWhenServerJsPresent",
                    line: 248
                  };
                  return __func(_, this, arguments, copyIisNodeWhenServerJsPresent, 0, __frame, function __$copyIisNodeWhenServerJsPresent() {
/*   249 */         log.silly("copyWebConfigWhenServerJsPresent");
                    return (function __$copyIisNodeWhenServerJsPresent(__then) {
/*   250 */           if ((!path.existsSync("iisnode.yml") && ((path.existsSync("server.js") || path.existsSync("app.js"))))) {
/*   251 */             log.info("Creating default iisnode.yml file");
/*   252 */             sourcePath = path.join(__dirname, "../templates/node/iisnode.yml");
/*   253 */             return fs.readFile(sourcePath, __cb(_, __frame, 5, 42, function ___(__0, __1) {
/*   253 */               return fs.writeFile("iisnode.yml", __1, __cb(_, __frame, 5, 14, __then, true));
                        }, true));
                      }
                       else {
                        __then();
                      }
                    ;
                    })(_);
                  });
                };
/*   257 */     function updateLocalConfigWithSiteName(_) {
                  var cfg;
                  var __frame = {
                    name: "updateLocalConfigWithSiteName",
                    line: 257
                  };
                  return __func(_, this, arguments, updateLocalConfigWithSiteName, 0, __frame, function __$updateLocalConfigWithSiteName() {
/*   258 */         log.silly("updateLocalConfigWithSiteName");
                    return (function __$updateLocalConfigWithSiteName(__then) {
/*   259 */           if (context.flags.isGitWorkingTree) {
/*   260 */             return site.readConfig(__cb(_, __frame, 3, 24, function ___(__0, __1) {
                          cfg = __1;
/*   261 */               cfg.name = context.site.name;
/*   262 */               cfg.webspace = context.site.webspace;
/*   263 */               return site.writeConfig(cfg, __cb(_, __frame, 6, 14, __then, true));
                        }, true));
                      }
                       else {
                        __then();
                      }
                    ;
                    })(_);
                  });
                };
/*   267 */     function createSiteAndInitializeRemoteRepo(_) {
                  var __frame = {
                    name: "createSiteAndInitializeRemoteRepo",
                    line: 267
                  };
                  return __func(_, this, arguments, createSiteAndInitializeRemoteRepo, 0, __frame, function __$createSiteAndInitializeRemoteRepo() {
/*   268 */         log.silly("createSiteAndInitializeRemoteRepo");
                    return (function __$createSiteAndInitializeRemoteRepo(__then) {
/*   269 */           if (!context.flags.siteExists) {
/*   270 */             return site.doSitesPost(context, __cb(_, __frame, 3, 14, function __$createSiteAndInitializeRemoteRepo() {
/*   271 */               return site.doRepositoryPost(context, __cb(_, __frame, 4, 14, function __$createSiteAndInitializeRemoteRepo() {
/*   272 */                 return site.doRepositoryGet(context, __cb(_, __frame, 5, 29, function ___(__0, __1) {
/*   272 */                   context.repo = __1;
                              __then();
                            }, true));
                          }, true));
                        }, true));
                      }
                       else {
/*   274 */             return site.doRepositoryGet(context, __cb(_, __frame, 7, 29, function ___(__0, __2) {
/*   274 */               context.repo = __2;
                          return (function __$createSiteAndInitializeRemoteRepo(__then) {
/*   275 */                 if (!context.repo) {
/*   276 */                   return site.doRepositoryPost(context, __cb(_, __frame, 9, 16, function __$createSiteAndInitializeRemoteRepo() {
/*   277 */                     return site.doRepositoryGet(context, __cb(_, __frame, 10, 31, function ___(__0, __3) {
/*   277 */                       context.repo = __3;
                                  __then();
                                }, true));
                              }, true));
                            }
                             else {
                              __then();
                            }
                          ;
                          })(__then);
                        }, true));
                      }
                    ;
                    })(function __$createSiteAndInitializeRemoteRepo() {
/*   280 */           log.silly("context.repo", context.repo);
                      _();
                    });
                  });
                };
/*   283 */     function addRemoteToLocalGitRepo(_) {
                  var remotes, azureExists, gitUri;
                  var __frame = {
                    name: "addRemoteToLocalGitRepo",
                    line: 283
                  };
                  return __func(_, this, arguments, addRemoteToLocalGitRepo, 0, __frame, function __$addRemoteToLocalGitRepo() {
/*   284 */         log.silly("addRemoteToLocalGitRepo");
/*   285 */         if (!context.flags.isGitWorkingTree) {
                      return _(null);
                    }
                  ;
                    return (function __$addRemoteToLocalGitRepo(__then) {
/*   289 */           if (context.c9) {
/*   290 */             context.publishingUsers = ["c9",];
/*   291 */             context.publishingUser = "c9";
                        __then();
                      }
                       else {
                        return (function __$addRemoteToLocalGitRepo(__then) {
/*   292 */               if (!context.publishingUser) {
/*   293 */                 return site.doPublishingUsersGet(context, __cb(_, __frame, 10, 40, function ___(__0, __1) {
/*   293 */                   context.publishingUsers = __1;
/*   294 */                   return getPublishingUser(context, __cb(_, __frame, 11, 39, function ___(__0, __2) {
/*   294 */                     context.publishingUser = __2;
                                __then();
                              }, true));
                            }, true));
                          }
                           else {
                            __then();
                          }
                        ;
                        })(__then);
                      }
                    ;
                    })(function __$addRemoteToLocalGitRepo() {
/*   297 */           log.verbose("Detecting git and local git folder");
/*   298 */           return exec("git remote", __cb(_, __frame, 15, 26, function ___(__0, __3) {
                        remotes = __3;
/*   299 */             azureExists = ((remotes.stdout + remotes.stderr)).split("\n").some(function(item) {
/*   300 */               return (item === "azure");
                        });
                        return (function __$addRemoteToLocalGitRepo(__then) {
/*   303 */               if (azureExists) {
/*   304 */                 log.verbose("Removing existing azure remote alias");
/*   305 */                 return exec("git remote rm azure", __cb(_, __frame, 22, 14, __then, true));
                          }
                           else {
                            __then();
                          }
                        ;
                        })(function __$addRemoteToLocalGitRepo() {
/*   308 */               gitUri = getGitUri(context.repo, context.site.name, context.publishingUser);
/*   309 */               log.info((("Executing `git remote add azure " + gitUri) + "`"));
/*   310 */               return exec(("git remote add azure " + gitUri), __cb(_, __frame, 27, 12, _, true));
                        });
                      }, true));
                    });
                  });
                };
                var __frame = {
                  name: "__2",
                  line: 119
                };
                return __func(_, this, arguments, __2, 2, __frame, function __$__2() {
/*   120 */       context = {
/*   121 */         subscription: cli.category("account").lookupSubscriptionId(options.subscription),
/*   122 */         git: options.git,
/*   123 */         c9: options.c9,
/*   124 */         site: {
/*   125 */           name: nameArg,
/*   126 */           webspace: options.location,
/*   127 */           hostname: options.hostname
                    },
/*   129 */         flags: {
                    }
                  };
/*   133 */       return promptForSiteName(__cb(_, __frame, 14, 10, function __$__2() {
/*   134 */         return determineIfSiteExists(__cb(_, __frame, 15, 10, function __$__2() {
/*   135 */           return promptForLocation(__cb(_, __frame, 16, 10, function __$__2() {
/*   136 */             return determineIfCurrentDirectoryIsGitWorkingTree(__cb(_, __frame, 17, 10, function __$__2() {
/*   137 */               return initGitOnCurrentDirectory(__cb(_, __frame, 18, 10, function __$__2() {
/*   138 */                 return copyIisNodeWhenServerJsPresent(__cb(_, __frame, 19, 10, function __$__2() {
/*   139 */                   return updateLocalConfigWithSiteName(__cb(_, __frame, 20, 10, function __$__2() {
/*   140 */                     return createSiteAndInitializeRemoteRepo(__cb(_, __frame, 21, 10, function __$__2() {
/*   141 */                       return addRemoteToLocalGitRepo(__cb(_, __frame, 22, 10, _, true));
                                }, true));
                              }, true));
                            }, true));
                          }, true));
                        }, true));
                      }, true));
                    }, true));
                  }, true));
                });
              });
/*   314 */   function portalCreateSiteInstruction(context, _) {
                var href;
                var __frame = {
                  name: "portalCreateSiteInstruction",
                  line: 314
                };
                return __func(_, this, arguments, portalCreateSiteInstruction, 1, __frame, function __$portalCreateSiteInstruction() {
/*   315 */       log.help("You must create your first web site using the Windows Azure portal.");
/*   316 */       log.help("Please follow these steps in the portal:");
/*   317 */       log.help("1. At the bottom of the page, click on New > Web Site > Quick Create");
/*   318 */       log.help((("2. Type \"" + ((((context.site && context.site.name)) || "{site name}"))) + "\" in the URL field"));
/*   319 */       log.help("3. Click on \"Create Web Site\"");
/*   320 */       log.help("4. Once the site has been created, click on the site name");
/*   321 */       log.help("5. Click on \"Set up Git publishing\" and create a publishing username and password. Use those credentials for all new websites you create.");
/*   322 */       if (context.git) {
/*   323 */         log.help("6. Back in the console window, rerun this command by typing \"azure site create {site name} --git\"");
                  }
                ;
/*   326 */       return confirm("Launch browser to portal now? (y/n) ", __cb(_, __frame, 12, 8, function ___(__0, __1) {
                    return (function __$portalCreateSiteInstruction(__then) {
                      if (__1) {
/*   327 */             log.help("Launching portal.");
/*   328 */             href = utils.portal();
/*   329 */             common.launchBrowser(href);
                        __then();
                      }
                       else {
                        __then();
                      }
                    ;
                    })(_);
                  }, true));
                });
              };
/*   333 */   function getPublishingUser(context, _) {
                var publishingUsers, filters;
                var __frame = {
                  name: "getPublishingUser",
                  line: 333
                };
                return __func(_, this, arguments, getPublishingUser, 1, __frame, function __$getPublishingUser() {
/*   334 */       publishingUsers = toArray(context.publishingUsers);
/*   335 */       filters = publishingUsers.filter(function(item) {
/*   336 */         return ((typeof item === "string") && (item.length <= 64));
                  });
                  return (function __$getPublishingUser(__then) {
/*   339 */         if ((filters.length === 0)) {
/*   340 */           return portalGitInitInstruction(context, __cb(_, __frame, 7, 6, function __$getPublishingUser() {
/*   341 */             return _(new Error("Git credentials needs to be setup on the portal"));
                      }, true));
                    }
                     else {
/*   342 */           if (((publishingUsers.length === 1) && (filters.length === 1))) {
/*   343 */             return _(null, filters[0]);
                      }
                    ;
                      __then();
                    }
                  ;
                  })(function __$getPublishingUser() {
/*   346 */         log.help("Please provide the username for Git deployment.");
/*   347 */         log.help("If you don't have one, please configure it in the management portal.");
/*   348 */         return prompt("Publishing username: ", __cb(_, __frame, 15, 11, _, true));
                  });
                });
              };
/*   351 */   function portalGitInitInstruction(context, _) {
                var href;
                var __frame = {
                  name: "portalGitInitInstruction",
                  line: 351
                };
                return __func(_, this, arguments, portalGitInitInstruction, 1, __frame, function __$portalGitInitInstruction() {
/*   352 */       log.help("You must create your git publishing credentials using the Windows Azure portal.");
/*   353 */       log.help("Please follow these steps in the portal:");
/*   354 */       log.help("1. In the menu on the left select \"Web Sites\"");
/*   355 */       log.help((("2. Click on the site named \"" + ((((context.site && context.site.name)) || "{site name}"))) + "\" or any other site"));
/*   356 */       log.help("3. Click on \"Set up Git publishing\" and create a publishing username and password. Use those credentials for all new websites you create.");
/*   357 */       if (context.git) {
/*   358 */         log.help("4. Back in the console window, rerun this command by typing \"azure site create {site name} --git\"");
                  }
                ;
/*   361 */       return confirm("Launch browser to portal now? (y/n) ", __cb(_, __frame, 10, 8, function ___(__0, __1) {
                    return (function __$portalGitInitInstruction(__then) {
                      if (__1) {
/*   362 */             log.help("Launching portal.");
/*   363 */             href = utils.portal();
/*   364 */             common.launchBrowser(href);
                        __then();
                      }
                       else {
                        __then();
                      }
                    ;
                    })(_);
                  }, true));
                });
              };
/*   368 */   var location = site.category("location").description("Commands to manage your Azure locations");
/*   371 */   location.command("list").whiteListPowershell().description("List locations available for your account").execute(function __3(options, _) {
                var context, spaces, s;
                var __frame = {
                  name: "__3",
                  line: 374
                };
                return __func(_, this, arguments, __3, 1, __frame, function __$__3() {
/*   375 */       context = {
/*   376 */         subscription: cli.category("account").lookupSubscriptionId(options.subscription)
                  };
/*   379 */       return site.doSpacesGet(context, __cb(_, __frame, 5, 23, function ___(__0, __1) {
                    spaces = __1;
                    return (function __$__3(__then) {
/*   380 */           if ((spaces && spaces.length)) {
/*   381 */             for (s in spaces) {
/*   382 */               spaces[s] = clean(spaces[s]);
                        };
/*   385 */             log.table(spaces, function(row, item) {
/*   386 */               row.cell("Name", item.Name);
/*   387 */               row.cell("Display Name", item.GeoRegion);
                        });
                        __then();
                      }
                       else {
/*   390 */             return portalCreateSiteInstruction(context, __cb(_, __frame, 16, 12, __then, true));
                      }
                    ;
                    })(_);
                  }, true));
                });
              });
/*   394 */   site.command("portal [name]").whiteListPowershell().description("Opens the portal in a browser to manage your web sites").execute(function __4(name, options, _) {
                var href;
                var __frame = {
                  name: "__4",
                  line: 397
                };
                return __func(_, this, arguments, __4, 2, __frame, function __$__4() {
/*   399 */       href = utils.portal();
/*   400 */       if (name) {
/*   401 */         href = (((href + "#Workspaces/WebsiteExtension/Website/") + name) + "/dashboard");
                  }
                ;
/*   404 */       common.launchBrowser(href);
                  _();
                });
              });
/*   407 */   site.command("browse [name]").whiteListPowershell().description("Open your web site in a browser.").option("-s, --subscription <id>", "use the subscription id").execute(function __5(name, options, _) {
                var context, cache, siteData, href;
                var __frame = {
                  name: "__5",
                  line: 411
                };
                return __func(_, this, arguments, __5, 2, __frame, function __$__5() {
/*   413 */       context = {
/*   414 */         subscription: cli.category("account").lookupSubscriptionId(options.subscription),
/*   415 */         site: {
/*   416 */           name: name
                    }
                  };
/*   420 */       return lookupSiteNameAndWebSpace(context, __cb(_, __frame, 9, 22, function ___(__0, __2) {
                    cache = __2;
                    return (function __$__5(_) {
/*   421 */           var __1 = cache;
                      if (__1) {
                        return _(null, __1);
                      }
                    ;
/*   421 */           return site.doSiteGet(context, __cb(_, __frame, 10, 40, _, true));
                    })(__cb(_, __frame, -410, 17, function ___(__0, __3) {
/*   421 */           siteData = clean(__3);
/*   423 */           href = ("http://" + toArray(siteData.HostNames)[0]);
/*   425 */           common.launchBrowser(href);
                      _();
                    }, true));
                  }, true));
                });
              });
/*   428 */   site.command("show [name]").whiteListPowershell().description("Show details for a web site").option("-s, --subscription <id>", "use the subscription id").execute(function __6(name, options, _) {
                var context, result, repositoryUri, gitUri, data;
                var __frame = {
                  name: "__6",
                  line: 432
                };
                return __func(_, this, arguments, __6, 2, __frame, function __$__6() {
/*   433 */       context = {
/*   434 */         subscription: cli.category("account").lookupSubscriptionId(options.subscription),
/*   435 */         site: {
/*   436 */           name: name
                    }
                  };
/*   440 */       return lookupSiteNameAndWebSpace(context, __cb(_, __frame, 8, 10, function __$__6() {
/*   442 */         log.info("Showing details for site");
/*   443 */         log.verbose("Parameters", context);
/*   445 */         return async.parallel([function __1(_) {
                      var __frame = {
                        name: "__1",
                        line: 446
                      };
                      return __func(_, this, arguments, __1, 0, __frame, function __$__1() {
/*   446 */             return site.doSiteGet(context, __cb(_, __frame, 0, 34, _, true));
                      });
/*   447 */         },function __2(_) {
                      var __frame = {
                        name: "__2",
                        line: 447
                      };
                      return __func(_, this, arguments, __2, 0, __frame, function __$__2() {
/*   447 */             return site.doSiteConfigGet(context, __cb(_, __frame, 0, 34, _, true));
                      });
                    },], __cb(_, __frame, 13, 23, function ___(__0, __3) {
                      result = __3;
/*   451 */           repositoryUri = getRepositoryUri(result[0]);
/*   452 */           gitUri = (repositoryUri ? getGitUri(repositoryUri, context.site.name) : "none");
/*   454 */           if (log.format().json) {
/*   455 */             data = {
/*   456 */               site: clean(result[0]),
/*   457 */               config: clean(result[1]),
/*   458 */               gitRepositoryUri: gitUri
                        };
/*   461 */             log.json(data);
                      }
/*   462 */            else {
/*   463 */             logEachData("Site", result[0]);
/*   464 */             logEachData("Config", result[1]);
/*   466 */             log.data("GitRepositoryUri", gitUri);
                      }
                    ;
                      _();
                    }, true));
                  }, true));
                });
              });
/*   470 */   function lookupSiteName(context, _) {
                var cfg;
                var __frame = {
                  name: "lookupSiteName",
                  line: 470
                };
                return __func(_, this, arguments, lookupSiteName, 1, __frame, function __$lookupSiteName() {
/*   471 */       if ((context.site.name !== undefined)) {
                    return _(null);
                  }
                ;
/*   476 */       return site.readConfig(__cb(_, __frame, 6, 14, function ___(__0, __1) {
                    cfg = __1;
/*   477 */         if ((cfg && cfg.name)) {
/*   479 */           context.site.name = cfg.name;
/*   480 */           context.site.webspace = cfg.webspace;
                      return _(null);
                    }
                  ;
/*   484 */         return prompt("Web site name: ", __cb(_, __frame, 14, 24, function ___(__0, __2) {
/*   484 */           context.site.name = __2;
/*   486 */           if (!context.site.name) {
/*   487 */             return _(new Error("Invalid site name"));
                      }
                    ;
                      _();
                    }, true));
                  }, true));
                });
              };
/*   491 */   function lookupSiteWebSpace(context, _) {
                var sites, index;
                var __frame = {
                  name: "lookupSiteWebSpace",
                  line: 491
                };
                return __func(_, this, arguments, lookupSiteWebSpace, 1, __frame, function __$lookupSiteWebSpace() {
/*   492 */       log.verbose("Attempting to locate site ", context.site.name);
/*   493 */       return site.doSitesGet(context, __cb(_, __frame, 2, 16, function ___(__0, __1) {
                    sites = __1;
/*   494 */         for (index in sites) {
/*   495 */           if (utils.ignoreCaseEquals(sites[index].Name, context.site.name)) {
/*   496 */             log.verbose("Site located at ", sites[index].WebSpace);
/*   497 */             context.site.webspace = sites[index].WebSpace;
                      }
                    ;
                    };
/*   500 */         if ((context.site.webspace === undefined)) {
/*   501 */           return _(new Error(("Unable to locate site named " + context.site.name)));
                    }
                  ;
                    _();
                  }, true));
                });
              };
/*   505 */   function lookupSiteNameAndWebSpace(context, _) {
                var cache;
                var __frame = {
                  name: "lookupSiteNameAndWebSpace",
                  line: 505
                };
                return __func(_, this, arguments, lookupSiteNameAndWebSpace, 1, __frame, function __$lookupSiteNameAndWebSpace() {
/*   506 */       return lookupSiteName(context, __cb(_, __frame, 1, 4, function __$lookupSiteNameAndWebSpace() {
/*   507 */         return cacheUtils.readSite(context, __cb(_, __frame, 2, 16, function ___(__0, __1) {
                      cache = __1;
/*   508 */           if ((cache || context.site.webspace)) {
/*   509 */             context.site.webspace = (((cache && cache.WebSpace)) || context.site.webspace);
/*   510 */             return _(null, cache);
                      }
                    ;
/*   512 */           return lookupSiteWebSpace(context, __cb(_, __frame, 7, 4, _, true));
                    }, true));
                  }, true));
                });
              };
/*   515 */   site.lookupSiteNameAndWebSpace = lookupSiteNameAndWebSpace;
/*   517 */   function getRepositoryUri(siteData) {
/*   518 */     if (siteData.SiteProperties.Properties) {
/*   519 */       for (var i = 0; (i < siteData.SiteProperties.Properties.NameValuePair.length); ++i) {
/*   520 */         var pair = siteData.SiteProperties.Properties.NameValuePair[i];
/*   521 */         if (utils.ignoreCaseEquals(pair.Name, "RepositoryUri")) {
/*   522 */           if ((typeof pair.Value === "string")) {
/*   523 */             if (!endsWith(pair.Value, "/")) {
/*   525 */               pair.Value += "/";
                        }
                      ;
/*   528 */             return pair.Value;
                      }
/*   529 */            else {
/*   530 */             return null;
                      }
                    ;
                    }
                  ;
                  };
                }
              ;
/*   536 */     return null;
              };
/*   539 */   site.getRepositoryUri = getRepositoryUri;
/*   541 */   function getGitUri(repositoryUri, siteName, auth) {
/*   542 */     var repoUrl = url.parse(repositoryUri);
/*   544 */     if (auth) {
/*   545 */       repoUrl.auth = auth;
                }
              ;
/*   548 */     var sitePath = (siteName + ".git");
/*   550 */     if (!endsWith(repoUrl.path, "/")) {
/*   552 */       repoUrl.path += "/";
                }
              ;
/*   554 */     repoUrl.path += sitePath;
/*   556 */     if (!endsWith(repoUrl.pathname, "/")) {
/*   558 */       repoUrl.pathname += "/";
                }
              ;
/*   560 */     repoUrl.pathname += sitePath;
/*   562 */     return url.format(repoUrl);
              };
/*   565 */   function getRepositoryAuth(siteData) {
/*   566 */     var userName, password;
/*   567 */     for (var i = 0; (i < siteData.SiteProperties.Properties.NameValuePair.length); ++i) {
/*   568 */       var pair = siteData.SiteProperties.Properties.NameValuePair[i];
/*   569 */       if (utils.ignoreCaseEquals(pair.Name, "PublishingUsername")) {
/*   570 */         userName = pair.Value;
                  }
/*   571 */        else if (utils.ignoreCaseEquals(pair.Name, "PublishingPassword")) {
/*   572 */         password = pair.Value;
                  }
                  
                ;
                };
/*   575 */     return (userName && (((userName + ":") + password)));
              };
/*   577 */   site.getRepositoryAuth = getRepositoryAuth;
/*   579 */   site.command("delete [name]").whiteListPowershell().description("Delete a web site").option("-s, --subscription <id>", "use the subscription id").option("-q, --quiet", "quiet mode, do not ask for delete confirmation").execute(function __7(name, options, _) {
                var context, progress, result;
                var __frame = {
                  name: "__7",
                  line: 584
                };
                return __func(_, this, arguments, __7, 2, __frame, function __$__7() {
/*   585 */       context = {
/*   586 */         subscription: cli.category("account").lookupSubscriptionId(options.subscription),
/*   587 */         site: {
/*   588 */           name: name
                    }
                  };
/*   592 */       return lookupSiteNameAndWebSpace(context, __cb(_, __frame, 8, 10, function __$__7() {
/*   594 */         log.info("Deleting site", context.site.name);
                    return (function __$__7(_) {
/*   595 */           var __1 = !options.quiet;
                      if (!__1) {
                        return _(null, __1);
                      }
                    ;
/*   595 */           return confirm((("Delete " + context.site.name) + " site?  (y/n) "), __cb(_, __frame, 11, 33, function ___(__0, __3) {
/*   595 */             var __2 = !__3;
                        return _(null, __2);
                      }, true));
                    })(__cb(_, __frame, -583, 17, function ___(__0, __2) {
                      return (function __$__7(__then) {
                        if (__2) {
                          return _(null);
                        }
                         else {
                          __then();
                        }
                      ;
                      })(function __$__7() {
/*   599 */             progress = cli.progress("Deleting site");
                        return (function ___(__then) {
                          (function ___(_) {
                            __tryCatch(_, function __$__7() {
/*   608 */                   return getChannel().path(context.subscription).path("services").path("webspaces").path(context.site.webspace).path("sites").path(context.site.name).DELETE(__cb(_, __frame, 24, 25, function ___(__0, __3) {
                                result = __3;
/*   609 */                     return cacheUtils.deleteSite(context, __cb(_, __frame, 25, 12, function __$__7() {
                                  _(null, null, true);
                                }, true));
                              }, true));
                            });
                          })(function ___(__e, __r, __cont) {
                            (function ___(__then) {
                              __tryCatch(_, function __$__7() {
/*   612 */                     progress.end();
                                __then();
                              });
                            })(function ___() {
                              __tryCatch(_, function ___() {
                                if (__cont) {
                                  __then();
                                } else {
                                  _(__e, __r);
                                };
                              });
                            });
                          });
                        })(function ___() {
                          __tryCatch(_, function __$__7() {
/*   614 */                 log.info((("Site " + context.site.name) + " has been deleted"));
                            _();
                          });
                        });
                      });
                    }, true));
                  }, true));
                });
              });
/*   618 */   site.command("start [name]").whiteListPowershell().description("Start a web site").option("-s, --subscription <id>", "use the subscription id").execute(function __8(name, options, _) {
                var context, progress, result;
                var __frame = {
                  name: "__8",
                  line: 622
                };
                return __func(_, this, arguments, __8, 2, __frame, function __$__8() {
/*   623 */       context = {
/*   624 */         subscription: cli.category("account").lookupSubscriptionId(options.subscription),
/*   625 */         site: {
/*   626 */           name: name
                    }
                  };
/*   630 */       return lookupSiteNameAndWebSpace(context, __cb(_, __frame, 8, 10, function __$__8() {
/*   632 */         log.info("Starting site", context.site.name);
/*   634 */         progress = cli.progress("Updating site state");
                    return (function ___(__then) {
                      (function ___(_) {
                        __tryCatch(_, function __$__8() {
/*   644 */               return getChannel().path(context.subscription).path("services").path("webspaces").path(context.site.webspace).path("sites").path(context.site.name).header("Content-Type", "application/xml").PUT(function(req) {
/*   645 */                 req.write("<Site xmlns=\"http://schemas.microsoft.com/windowsazure\">");
/*   646 */                 req.write("<HostNames>");
/*   647 */                 req.write("<string xmlns=\"http://schemas.microsoft.com/2003/10/Serialization/Arrays\">");
/*   648 */                 req.write((context.site.name + cli.category("account").hostNameSuffix()));
/*   649 */                 req.write("</string>");
/*   650 */                 req.write("</HostNames>");
/*   651 */                 req.write("<Name>");
/*   652 */                 req.write(context.site.name);
/*   653 */                 req.write("</Name>");
/*   654 */                 req.write("<State>");
/*   655 */                 req.write("Running");
/*   656 */                 req.write("</State>");
/*   657 */                 req.write("</Site>");
/*   659 */                 req.end();
                          }, __cb(_, __frame, 22, 25, function ___(__0, __1) {
                            result = __1;
                            _(null, null, true);
                          }, true));
                        });
                      })(function ___(__e, __r, __cont) {
                        (function ___(__then) {
                          __tryCatch(_, function __$__8() {
/*   663 */                 progress.end();
                            __then();
                          });
                        })(function ___() {
                          __tryCatch(_, function ___() {
                            if (__cont) {
                              __then();
                            } else {
                              _(__e, __r);
                            };
                          });
                        });
                      });
                    })(function ___() {
                      __tryCatch(_, function __$__8() {
/*   666 */             log.info((("Site " + context.site.name) + " has been started"));
                        _();
                      });
                    });
                  }, true));
                });
              });
/*   669 */   site.command("stop [name]").whiteListPowershell().description("Stop a web site").option("-s, --subscription <id>", "use the subscription id").execute(function __9(name, options, _) {
                var context, progress, result;
                var __frame = {
                  name: "__9",
                  line: 673
                };
                return __func(_, this, arguments, __9, 2, __frame, function __$__9() {
/*   674 */       context = {
/*   675 */         subscription: cli.category("account").lookupSubscriptionId(options.subscription),
/*   676 */         site: {
/*   677 */           name: name
                    }
                  };
/*   681 */       return lookupSiteNameAndWebSpace(context, __cb(_, __frame, 8, 10, function __$__9() {
/*   683 */         log.info("Stopping site", context.site.name);
/*   685 */         progress = cli.progress("Updating site state");
                    return (function ___(__then) {
                      (function ___(_) {
                        __tryCatch(_, function __$__9() {
/*   695 */               return getChannel().path(context.subscription).path("services").path("webspaces").path(context.site.webspace).path("sites").path(context.site.name).header("Content-Type", "application/xml").PUT(function(req) {
/*   696 */                 req.write("<Site xmlns=\"http://schemas.microsoft.com/windowsazure\">");
/*   697 */                 req.write("<HostNames>");
/*   698 */                 req.write("<string xmlns=\"http://schemas.microsoft.com/2003/10/Serialization/Arrays\">");
/*   699 */                 req.write((context.site.name + cli.category("account").hostNameSuffix()));
/*   700 */                 req.write("</string>");
/*   701 */                 req.write("</HostNames>");
/*   702 */                 req.write("<Name>");
/*   703 */                 req.write(context.site.name);
/*   704 */                 req.write("</Name>");
/*   705 */                 req.write("<State>");
/*   706 */                 req.write("Stopped");
/*   707 */                 req.write("</State>");
/*   708 */                 req.write("</Site>");
/*   710 */                 req.end();
                          }, __cb(_, __frame, 22, 25, function ___(__0, __1) {
                            result = __1;
                            _(null, null, true);
                          }, true));
                        });
                      })(function ___(__e, __r, __cont) {
                        (function ___(__then) {
                          __tryCatch(_, function __$__9() {
/*   714 */                 progress.end();
                            __then();
                          });
                        })(function ___() {
                          __tryCatch(_, function ___() {
                            if (__cont) {
                              __then();
                            } else {
                              _(__e, __r);
                            };
                          });
                        });
                      });
                    })(function ___() {
                      __tryCatch(_, function __$__9() {
/*   717 */             log.info((("Site " + context.site.name) + " has been stopped"));
                        _();
                      });
                    });
                  }, true));
                });
              });
/*   724 */   site.readConfig = function site_readConfig__10(_) {
                var __frame = {
                  name: "site_readConfig__10",
                  line: 724
                };
                return __func(_, this, arguments, site_readConfig__10, 0, __frame, function __$site_readConfig__10() {
/*   726 */       return site.readConfigValue("azure.site.name", __cb(_, __frame, 2, 12, function ___(__0, __2) {
/*   727 */         return site.readConfigValue("azure.site.webspace", __cb(_, __frame, 3, 16, function ___(__0, __3) {
/*   725 */           var __1 = {
/*   726 */             name: __2,
/*   727 */             webspace: __3
                      };
                      return _(null, __1);
                    }, true));
                  }, true));
                });
              };
/*   731 */   site.writeConfig = function site_writeConfig__11(cfg, _) {
                var __frame = {
                  name: "site_writeConfig__11",
                  line: 731
                };
                return __func(_, this, arguments, site_writeConfig__11, 1, __frame, function __$site_writeConfig__11() {
/*   732 */       return site.writeConfigValue("azure.site.name", cfg.name, __cb(_, __frame, 1, 4, function __$site_writeConfig__11() {
/*   733 */         return site.writeConfigValue("azure.site.webspace", cfg.webspace, __cb(_, __frame, 2, 4, _, true));
                  }, true));
                });
              };
/*   736 */   site.readConfigValue = function site_readConfigValue__12(name, _) {
                var result;
                var __frame = {
                  name: "site_readConfigValue__12",
                  line: 736
                };
                return __func(_, this, arguments, site_readConfigValue__12, 1, __frame, function __$site_readConfigValue__12() {
                  return (function ___(__then) {
                    (function ___(_) {
                      __tryCatch(_, function __$site_readConfigValue__12() {
/*   738 */             return exec(("git config --get " + name), __cb(_, __frame, 2, 19, function ___(__0, __1) {
                          result = __1;
/*   739 */               return _(null, ((result.stdout + result.stderr)).trim());
                        }, true));
                      });
                    })(function ___(err, __result) {
                      __tryCatch(_, function __$site_readConfigValue__12() {
                        if (err) {
/*   742 */               log.silly("Unable to read config", err);
/*   743 */               return _(null, "");
                        }
                         else {
                          _(null, __result);
                        }
                      ;
                      });
                    });
                  })(function ___() {
                    __tryCatch(_, _);
                  });
                });
              };
/*   747 */   site.writeConfigValue = function site_writeConfigValue__13(name, value, _) {
                var __frame = {
                  name: "site_writeConfigValue__13",
                  line: 747
                };
                return __func(_, this, arguments, site_writeConfigValue__13, 2, __frame, function __$site_writeConfigValue__13() {
/*   748 */       return exec(((("git config " + name) + " ") + value), __cb(_, __frame, 1, 4, _, true));
                });
              };
/*   755 */   site.doSitesPost = function(options, callback) {
/*   756 */     log.info((("Creating a new web site at " + options.site.name) + cli.category("account").hostNameSuffix()));
/*   757 */     log.verbose("Subscription", options.subscription);
/*   758 */     log.verbose("Webspace", options.site.webspace);
/*   759 */     log.verbose("Site", options.site.name);
/*   761 */     var progress = cli.progress("Sending site information");
/*   762 */     getChannel().path(options.subscription).path("services").path("webspaces").path(options.site.webspace).path("sites").header("Content-Type", "application/xml").POST(writers.Site.xml(options.site), function(err, result) {
/*   772 */       progress.end();
/*   773 */       if (err) {
/*   774 */         logError("Failed to create site", err);
                  }
/*   775 */        else {
/*   776 */         return cacheUtils.saveSite(options, result, function(err) {
/*   777 */           log.info(("Created website at " + clean(result).HostNames));
/*   778 */           log.verbose("Site", clean(result));
/*   779 */           return callback(err, result);
                    });
                  }
                ;
/*   782 */       return callback(err, result);
                });
              };
/*   786 */   site.doRepositoryPost = function(options, callback) {
/*   787 */     log.info("Initializing remote Azure repository");
/*   788 */     log.verbose("Subscription", options.subscription);
/*   789 */     log.verbose("Webspace", options.site.webspace);
/*   790 */     log.verbose("Site", options.site.name);
/*   792 */     var progress = cli.progress("Updating site information");
/*   793 */     getChannel().path(options.subscription).path("services").path("webspaces").path(options.site.webspace).path("sites").path(options.site.name).path("repository").POST("", function(err, result) {
/*   804 */       progress.end();
/*   805 */       if (err) {
/*   806 */         logError("Failed to initialize repository", err);
                  }
/*   807 */        else {
/*   808 */         log.info("Repository initialized");
                  }
                ;
/*   810 */       return callback(err, result);
                });
              };
/*   814 */   site.doSpacesGet = function site_doSpacesGet__14(options, _) {
                var progress, result, spaces;
                var __frame = {
                  name: "site_doSpacesGet__14",
                  line: 814
                };
                return __func(_, this, arguments, site_doSpacesGet__14, 1, __frame, function __$site_doSpacesGet__14() {
/*   815 */       log.verbose("Subscription", options.subscription);
/*   817 */       progress = cli.progress("Enumerating locations");
                  return (function ___(__then) {
                    (function ___(_) {
                      __tryCatch(_, function __$site_doSpacesGet__14() {
/*   824 */             return getChannel().path(options.subscription).path("services").path("webspaces").path("").GET(__cb(_, __frame, 10, 19, function ___(__0, __1) {
                          result = __1;
/*   826 */               log.json("silly", result);
/*   827 */               spaces = toArray(result.WebSpace);
/*   828 */               return cacheUtils.saveSpaces(options, spaces, __cb(_, __frame, 14, 6, function __$site_doSpacesGet__14() {
/*   829 */                 return _(null, spaces);
                          }, true));
                        }, true));
                      });
                    })(function ___(__e, __r, __cont) {
                      (function ___(__then) {
                        __tryCatch(_, function __$site_doSpacesGet__14() {
/*   832 */               progress.end();
                          __then();
                        });
                      })(function ___() {
                        __tryCatch(_, function ___() {
                          if (__cont) {
                            __then();
                          } else {
                            _(__e, __r);
                          };
                        });
                      });
                    });
                  })(function ___() {
                    __tryCatch(_, _);
                  });
                });
              };
/*   836 */   site.doSitesGet = function site_doSitesGet__15(options, _) {
                var spaces, channel, progress, result, sites;
                var __frame = {
                  name: "site_doSitesGet__15",
                  line: 836
                };
                return __func(_, this, arguments, site_doSitesGet__15, 1, __frame, function __$site_doSitesGet__15() {
/*   837 */       log.verbose("Subscription", options.subscription);
/*   839 */       return site.doSpacesGet(options, __cb(_, __frame, 3, 17, function ___(__0, __2) {
                    spaces = __2;
/*   844 */         channel = getChannel().path(options.subscription).path("services").path("webspaces");
/*   846 */         progress = cli.progress("Enumerating sites");
                    return (function ___(__then) {
                      (function ___(_) {
                        __tryCatch(_, function __$site_doSitesGet__15() {
/*   848 */               return async.map(spaces, function __1(webspace, _) {
                            var __frame = {
                              name: "__1",
                              line: 850
                            };
                            return __func(_, this, arguments, __1, 1, __frame, function __$__1() {
/*   856 */                   return channel.path(webspace.Name).path("sites").path("").query("propertiesToInclude", "repositoryuri,publishingpassword,publishingusername").GET(__cb(_, __frame, 6, 25, _, true));
                            });
                          }, __cb(_, __frame, 12, 19, function ___(__0, __3) {
                            result = __3;
/*   860 */                 sites = [];
/*   861 */                 result.forEach(function(item) {
/*   862 */                   sites = sites.concat(toArray(item.Site));
                            });
/*   864 */                 result = sites;
/*   866 */                 log.json("verbose", sites);
/*   867 */                 return cacheUtils.saveSites(options, result, __cb(_, __frame, 31, 6, function __$site_doSitesGet__15() {
/*   868 */                   return _(null, sites);
                            }, true));
                          }, true));
                        });
                      })(function ___(__e, __r, __cont) {
                        (function ___(__then) {
                          __tryCatch(_, function __$site_doSitesGet__15() {
/*   871 */                 progress.end();
                            __then();
                          });
                        })(function ___() {
                          __tryCatch(_, function ___() {
                            if (__cont) {
                              __then();
                            } else {
                              _(__e, __r);
                            };
                          });
                        });
                      });
                    })(function ___() {
                      __tryCatch(_, _);
                    });
                  }, true));
                });
              };
/*   875 */   site.doSiteGet = function(options, callback) {
/*   876 */     var progress = cli.progress("Retrieving site information");
/*   877 */     getChannel().path(options.subscription).path("services").path("webspaces").path(options.site.webspace).path("sites").path(options.site.name).query("propertiesToInclude", "repositoryuri,publishingpassword,publishingusername").GET(function(err, result) {
/*   887 */       progress.end();
/*   888 */       if (err) {
/*   889 */         logError("Failed to get site info", err);
/*   890 */         if ((err.Code === "NotFound")) {
/*   891 */           return cacheUtils.deleteSite(options, function() {
/*   892 */             return callback(err, result);
                      });
                    }
                  ;
                  }
/*   895 */        else {
/*   896 */         return cacheUtils.saveSite(options, result, function(err) {
/*   897 */           log.verbose("Site", clean(result));
/*   898 */           return callback(err, result);
                    });
                  }
                ;
/*   901 */       return callback(err, result);
                });
              };
/*   905 */   site.doSiteConfigGet = function(options, callback) {
/*   906 */     var progress = cli.progress("Retrieving site config information");
/*   907 */     getChannel().path(options.subscription).path("services").path("webspaces").path(options.site.webspace).path("sites").path(options.site.name).path("config").GET(function(err, result) {
/*   917 */       progress.end();
/*   918 */       if (err) {
/*   919 */         logError("Failed to get site config info", err);
                  }
/*   920 */        else {
/*   921 */         log.verbose("SiteConfig", clean(result));
                  }
                ;
/*   923 */       return callback(err, result);
                });
              };
/*   927 */   site.doRepositoryGet = function site_doRepositoryGet__16(options, _) {
                var siteData;
                var __frame = {
                  name: "site_doRepositoryGet__16",
                  line: 927
                };
                return __func(_, this, arguments, site_doRepositoryGet__16, 1, __frame, function __$site_doRepositoryGet__16() {
/*   928 */       return site.doSiteGet(options, __cb(_, __frame, 1, 19, function ___(__0, __1) {
                    siteData = __1;
/*   929 */         return _(null, getRepositoryUri(siteData));
                  }, true));
                });
              };
/*   932 */   site.doPublishingUsersGet = function site_doPublishingUsersGet__17(options, _) {
                var progress, publishingUsers;
                var __frame = {
                  name: "site_doPublishingUsersGet__17",
                  line: 932
                };
                return __func(_, this, arguments, site_doPublishingUsersGet__17, 1, __frame, function __$site_doPublishingUsersGet__17() {
/*   933 */       progress = cli.progress("Retrieving user information");
                  return (function ___(__then) {
                    (function ___(_) {
                      __tryCatch(_, function __$site_doPublishingUsersGet__17() {
/*   941 */             return getChannel().path(options.subscription).path("services").path("webspaces").path("").query("properties", "publishingUsers").GET(__cb(_, __frame, 9, 34, function ___(__0, __1) {
/*   935 */               publishingUsers = clean(__1);
/*   943 */               log.verbose("PublishingUsers", publishingUsers);
/*   944 */               return _(null, publishingUsers);
                        }, true));
                      });
                    })(function ___(__e, __r, __cont) {
                      (function ___(__then) {
                        __tryCatch(_, function __$site_doPublishingUsersGet__17() {
/*   947 */               progress.end();
                          __then();
                        });
                      })(function ___() {
                        __tryCatch(_, function ___() {
                          if (__cont) {
                            __then();
                          } else {
                            _(__e, __r);
                          };
                        });
                      });
                    });
                  })(function ___() {
                    __tryCatch(_, _);
                  });
                });
              };
/*   955 */   var writers = {
/*   956 */     Site: {
/*   957 */       xml: function(site) {
/*   958 */         return function(req) {
/*   959 */           req.write("<Site xmlns=\"http://schemas.microsoft.com/windowsazure\">");
/*   960 */           req.write("<HostNames>");
/*   961 */           req.write("<string xmlns=\"http://schemas.microsoft.com/2003/10/Serialization/Arrays\">");
/*   962 */           req.write((site.name + cli.category("account").hostNameSuffix()));
/*   963 */           req.write("</string>");
/*   965 */           if (site.hostname) {
/*   966 */             req.write("<string xmlns=\"http://schemas.microsoft.com/2003/10/Serialization/Arrays\">");
/*   967 */             req.write(site.hostname);
/*   968 */             req.write("</string>");
                      }
                    ;
/*   970 */           req.write("</HostNames>");
/*   971 */           req.write("<Name>");
/*   972 */           req.write(site.name);
/*   973 */           req.write("</Name>");
/*   974 */           req.write("</Site>");
/*   976 */           req.end();
                    };
                  }
                }
              };
/*   982 */   function clean(source) {
/*   983 */     if ((typeof (source) === "string")) {
/*   984 */       return source;
                }
              ;
/*   987 */     var target = {
                };
/*   988 */     var hasString = false;
/*   989 */     var hasNonString = false;
/*   990 */     var stringValue = "";
/*   992 */     for (var prop in source) {
/*   993 */       if ((prop == "@")) {
/*   994 */         continue;
                  }
/*   995 */        else {
/*   996 */         if ((((prop === "#") || (prop === "string")) || (prop.substring((prop.length - 7)) === ":string"))) {
/*   997 */           hasString = true;
/*   998 */           stringValue = source[prop];
                    }
/*   999 */          else {
/*  1000 */           hasNonString = true;
                    }
                  ;
/*  1002 */         target[prop] = clean(source[prop]);
                  }
                ;
                };
/*  1005 */     if ((hasString && !hasNonString)) {
/*  1006 */       return stringValue;
                }
              ;
/*  1008 */     return target;
              };
/*  1011 */   function logEachData(title, data) {
/*  1012 */     var cleaned = clean(data);
/*  1013 */     for (var property in cleaned) {
/*  1014 */       log.data(((title + " ") + property), cleaned[property]);
                };
              };
/*  1017 */   site.logEachData = logEachData;
/*  1019 */   function logError(message, err) {
/*  1020 */     if ((arguments.length == 1)) {
/*  1021 */       err = message;
/*  1022 */       message = undefined;
                }
/*  1023 */      else {
/*  1024 */       log.error(message);
                }
              ;
/*  1027 */     if (err) {
/*  1028 */       if (err.message) {
/*  1030 */         log.verbose("stack", err.stack);
/*  1031 */         log.json("silly", err);
                  }
/*  1033 */        else if (err.Message) {
/*  1035 */         log.json("verbose", clean(err));
                  }
/*  1037 */        else {
                  
                  }
                  
                ;
                }
              ;
              };
/*  1043 */   function isArray(testObject) {
/*  1044 */     return (((testObject && !(testObject.propertyIsEnumerable("length"))) && (typeof testObject === "object")) && (typeof testObject.length === "number"));
              };
/*  1047 */   function toArray(testObject) {
/*  1048 */     return (isArray(testObject) ? testObject : ((typeof testObject === "undefined") ? [] : [testObject,]));
              };
/*  1051 */   function endsWith(str, suffix) {
/*  1052 */     return (str.indexOf(suffix, (str.length - suffix.length)) !== -1);
              };
/*  1055 */   function exec(cmd, cb) {
/*  1056 */     child_process.exec(cmd, function(err, stdout, stderr) {
/*  1057 */       cb(err, {
/*  1058 */         stdout: stdout,
/*  1059 */         stderr: stderr
                  });
                });
              };
            };
